version: '3.8'

services:
  app:
    build:
      context: .
    container_name: evoluir-backend
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./.docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env.local
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    container_name: evoluir-mysql
    ports:
      - 3306:3306
    env_file:
      - .env.local
    volumes:
      - ./.docker/data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: evoluir-phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env.local
    restart: always

volumes:
  db_data:
